# Generated by Django 5.2.5 on 2025-12-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('TECH', 'Technology'), ('PHIL', 'Philosophy'), ('SCI', 'Science'), ('SOC', 'Society'), ('ART', 'Art & Culture'), ('LIFE', 'Life & Self')], default='LIFE', max_length=4),
        ),
    ]
