# Generated by Django 5.2.5 on 2025-12-30 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='blog_commen_post_id_fe6079_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['topic'], name='blog_post_topic_95d650_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status'], name='blog_post_status_02ce19_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['date_posted'], name='blog_post_date_po_3dd414_idx'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
