# Generated by Django 5.2.5 on 2026-01-10 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('VIEW', 'View'), ('COMMENT', 'Comment')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together={('user', 'post', 'interaction_type')},
        ),
    ]
