# Generated by Django 5.2.5 on 2026-01-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_interaction_interaction_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together=set(),
        ),
    ]
