# Generated by Django 5.2.5 on 2026-01-28 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_post_id_fe6079_idx',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'date_posted'], name='blog_commen_post_id_7d31e2_idx'),
        ),
    ]
