# Generated by Django 5.2.5 on 2026-01-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_interests_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_soft_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='scheduled_deletion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
